# Generated by Django 4.2.2 on 2023-07-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='create_group_faculty_type',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='create_subject',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='edit_group',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='finance',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='send_message',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='working_with_applicant',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='working_with_student',
        ),
    ]
