# Generated by Django 4.2.2 on 2023-06-13 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_status_alter_user_type'),
        ('university', '0002_facultytype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yonalish',
        ),
        migrations.AddField(
            model_name='facultytype',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.faculty'),
        ),
    ]
