# Generated by Django 4.2.2 on 2023-06-17 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_delete_yonalish_facultytype_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='facultytype',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='facultytype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='facultytype',
            name='passing_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facultytype',
            name='subject1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_subject', to='university.subject'),
        ),
        migrations.AddField(
            model_name='facultytype',
            name='subject2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_subject', to='university.subject'),
        ),
        migrations.AddField(
            model_name='facultytype',
            name='subject3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_subject', to='university.subject'),
        ),
        migrations.AddField(
            model_name='facultytype',
            name='subject4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fourth_subject', to='university.subject'),
        ),
        migrations.AddField(
            model_name='facultytype',
            name='subject5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fifth_subject', to='university.subject'),
        ),
    ]
