# Generated by Django 4.2.2 on 2023-06-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_subject_passing_score_subject_test_file_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='name',
            new_name='admin_name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='admin_name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='passing_score',
            new_name='one_question_ball',
        ),
        migrations.AddField(
            model_name='faculty',
            name='site_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='question_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='site_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
