# Generated by Django 4.2.2 on 2023-06-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_rename_name_faculty_admin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='one_question_ball',
            field=models.FloatField(null=True),
        ),
    ]
