# Generated by Django 4.2.2 on 2023-06-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_alter_subject_one_question_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultytype',
            name='test_minute',
            field=models.IntegerField(default=0),
        ),
    ]
