# Generated by Django 4.2.2 on 2023-06-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_facultytype_test_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultytype',
            name='group_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='facultytype',
            name='group_students',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('students', models.IntegerField(default=0)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.faculty')),
                ('faculty_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.facultytype')),
            ],
        ),
    ]
