# Generated by Django 4.2.2 on 2023-06-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_facultytype_group_name_facultytype_group_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='group',
            name='faculty_type',
        ),
    ]
