# Generated by Django 4.2.2 on 2023-07-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_facultytype_contract_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultytype',
            name='description_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
