# Generated by Django 4.2.2 on 2023-07-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_facultytype_description_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.CharField(choices=[('1- Kurs', '1- Kurs'), ('2- Kurs', '2- Kurs'), ('3- Kurs', '3- Kurs'), ('4- Kurs', '4- Kurs')], default='1- Kurs', max_length=100),
        ),
    ]
