# Generated by Django 4.2.2 on 2023-07-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_group_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.CharField(choices=[('1-Kurs', '1-Kurs'), ('2-Kurs', '2-Kurs'), ('3-Kurs', '3-Kurs'), ('4-Kurs', '4-Kurs')], default='1-Kurs', max_length=100),
        ),
    ]
