# Generated by Django 4.2.2 on 2023-07-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0016_rename_description_file_facultytype_malumotnoma_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultytype',
            name='first_quarter',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='facultytype',
            name='second_quarter',
            field=models.DateField(null=True),
        ),
    ]
