# Generated by Django 4.2.2 on 2023-06-13 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_facultytype'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[("Ko'rib chiqilmoqda", "Ko'rib chiqilmoqda"), ('Tasdiqlandi', 'Tasdiqlandi'), ('Rad etildi', 'Rad etildi')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.facultytype'),
        ),
    ]
