# Generated by Django 4.2.2 on 2023-06-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_status_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diploma_seria',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Diplom Seriyasi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_seria',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Passport Seriyasi'),
        ),
    ]
