# Generated by Django 4.2.2 on 2023-06-14 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_delete_yonalish_facultytype_faculty'),
        ('users', '0003_user_diploma_seria_alter_user_passport_seria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_if_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='diploma_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='diploma_seria',
        ),
        migrations.RemoveField(
            model_name='user',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ielts_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_seria',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='study_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[("Ko'rib chiqilmoqda", "Ko'rib chiqilmoqda"), ('Tasdiqlandi', 'Tasdiqlandi'), ('Rad etildi', 'Rad etildi')], default="Ko'rib chiqilmoqda", max_length=50, null=True)),
                ('passport_seria', models.CharField(blank=True, max_length=150, null=True, verbose_name='Passport Seriyasi')),
                ('date_if_birth', models.DateField(blank=True, null=True)),
                ('diploma_seria', models.CharField(blank=True, max_length=150, null=True, verbose_name='Diplom Seriyasi')),
                ('diploma_picture', models.ImageField(null=True, upload_to='')),
                ('ielts_picture', models.ImageField(null=True, upload_to='')),
                ('acceptance_order', models.ImageField(null=True, upload_to='')),
                ('course_order', models.ImageField(null=True, upload_to='')),
                ('removal_order', models.ImageField(null=True, upload_to='')),
                ('academic_certificate', models.ImageField(null=True, upload_to='')),
                ('university_license', models.ImageField(null=True, upload_to='')),
                ('university_accreditation', models.ImageField(null=True, upload_to='')),
                ('application_type', models.CharField(choices=[("Ro'yxatdan o'tish", "Ro'yxatdan o'tish"), ("O'qishni ko'chirish", "O'qishni ko'chirish")], max_length=100)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.faculty')),
                ('study_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.studytype')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.facultytype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
