# Generated by Django 4.2.2 on 2023-06-14 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_date_if_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='second_phone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam Xalqaro Formatda 998YYXXXXXXX ko'rinishida kiritilishi kerak!", regex='(0|91)?[7-9][0-9]{9}')]),
        ),
    ]
