# Generated by Django 4.2.2 on 2023-06-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_application_academic_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(blank=True, choices=[("Ro'yxatdan o'tish", "Ro'yxatdan o'tish"), ("O'qishni ko'chirish", "O'qishni ko'chirish")], max_length=100, null=True),
        ),
    ]
