# Generated by Django 4.2.2 on 2023-06-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_application_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[("Ko'rib chiqilmoqda", "Ko'rib chiqilmoqda"), ('Tasdiqlandi', 'Tasdiqlandi'), ('Rad etildi', 'Rad etildi'), ('Konsultatsiya', 'Konsultatsiya')], default="Ko'rib chiqilmoqda", max_length=50, null=True),
        ),
    ]
