# Generated by Django 4.2.2 on 2023-06-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(blank=True, choices=[("Ro'yxatdan o'tish", "Ro'yxatdan o'tish"), ("O'qishni ko'chirish", "O'qishni ko'chirish"), ('Konsultatsiya', 'Konsultatsiya')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[("Ko'rib chiqilmoqda", "Ko'rib chiqilmoqda"), ('Tasdiqlandi', 'Tasdiqlandi'), ('Rad etildi', 'Rad etildi')], default="Ko'rib chiqilmoqda", max_length=50, null=True),
        ),
    ]
