# Generated by Django 4.2.2 on 2023-06-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_application_application_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
