# Generated by Django 4.2.2 on 2023-06-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='full name'),
        ),
    ]
