# Generated by Django 4.2.2 on 2023-07-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_group_faculty_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='create_subject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='edit_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='finance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='send_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='super_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='working_with_applicant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='working_with_student',
            field=models.BooleanField(default=False),
        ),
    ]
