# Generated by Django 4.2.2 on 2023-07-29 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0018_rename_contract_amount_facultytype_contract_amount1_and_more'),
        ('bot', '0002_botuser_is_registered_botuser_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='utp',
        ),
        migrations.CreateModel(
            name='UserTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utp', models.IntegerField(default=0)),
                ('mode', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Kunduzgi'), (2, 'Kechgi'), (3, 'Sirtqi')], default=0)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.faculty')),
                ('faculty_dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.facultytype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botuser')),
            ],
        ),
    ]
