# Generated by Django 4.2.3 on 2023-07-07 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0015_alter_group_course'),
        ('bot', '0002_botfaculty_botuser_is_admin_botuser_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField(default=0)),
                ('questionIndex', models.IntegerField(default=1)),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Current_Question', to='university.question')),
                ('questions', models.ManyToManyField(to='university.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botuser')),
            ],
        ),
    ]
