# Generated by Django 4.2.3 on 2023-07-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_testsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='questionCount',
            field=models.IntegerField(default=1),
        ),
    ]
