# Generated by Django 4.2.3 on 2023-07-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_testsession_questioncount'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
