# Generated by Django 4.2.2 on 2023-06-23 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_rename_name_faculty_admin_name_and_more'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_privilege',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='test_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TestSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('ball', models.FloatField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.subject')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.question')),
                ('student_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.answer')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.testsubject')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.application'),
        ),
    ]
