# Generated by Django 4.2.2 on 2023-06-25 06:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
