# Generated by Django 4.2.2 on 2023-07-02 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_application_full_name_application_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam Xalqaro Formatda 998YYXXXXXXX ko'rinishida kiritilishi kerak!", regex='(0|91)?[7-9][0-9]{9}')]),
        ),
    ]
