# Generated by Django 4.2.2 on 2023-07-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_full_name_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
