# Generated by Django 4.2.2 on 2023-07-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_application_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_finance_id',
            field=models.PositiveIntegerField(default=83294, editable=False, null=True, unique=True),
        ),
    ]
