# Generated by Django 4.2.2 on 2023-07-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_remove_student_user_finance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_finance_id',
            field=models.PositiveIntegerField(default=69864, editable=False, null=True, unique=True),
        ),
    ]
