# Generated by Django 4.2.2 on 2023-07-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_student_user_finance_id_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='file_path',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_finance_id',
            field=models.PositiveIntegerField(default=10066, editable=False, null=True, unique=True),
        ),
    ]
