# Generated by Django 4.2.2 on 2023-07-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_agreement_file_path_alter_student_user_finance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_finance_id',
            field=models.PositiveIntegerField(default=62763, editable=False, null=True, unique=True),
        ),
    ]
