# Generated by Django 4.2.2 on 2023-07-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_student_user_finance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='kurs_for',
            field=models.CharField(choices=[('1-Kurs', '1-Kurs'), ('2-Kurs', '2-Kurs'), ('3-Kurs', '3-Kurs')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_finance_id',
            field=models.PositiveIntegerField(default=65541, editable=False, null=True, unique=True),
        ),
    ]
