# Generated by Django 4.2.2 on 2023-07-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_application_kurs_for_alter_student_user_finance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_finance_id',
            field=models.PositiveIntegerField(default=53307, editable=False, null=True, unique=True),
        ),
    ]
