# Generated by Django 4.2.2 on 2023-07-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_student_user_finance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contract_amount1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='contract_amount2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('1-Kurs', '1-Kurs'), ('2-Kurs', '2-Kurs'), ('3-Kurs', '3-Kurs')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='first_quarter',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='second_quarter',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='kurs_for',
            field=models.CharField(choices=[('1-Kurs', '1-Kurs'), ('2-Kurs', '2-Kurs'), ('3-Kurs', '3-Kurs'), ('4-Kurs', '4-Kurs')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_finance_id',
            field=models.PositiveIntegerField(default=57421, editable=False, null=True, unique=True),
        ),
    ]
