# Generated by Django 4.2.2 on 2023-07-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_student_contract_amount1_student_contract_amount2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_finance_id',
            field=models.PositiveIntegerField(default=15931, editable=False, null=True, unique=True),
        ),
    ]
